name: Padavan CI PSG1218
on:              
  watch:                          
    types: [started]                 

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id  
    steps:
    - name: Checkout Master            
      uses: actions/checkout@master
    - name: Initialization Environment 
      env:
        DEBIAN_FRONTEND: noninteractive  
      run: |
        sudo apt-get update
        sudo apt-get install git autopoint autoconf automake bison build-essential flex gawk gettext gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils mc
    - name: Clone Code                 
      run: |
        git clone --depth=1 https://bitbucket.org/padavan/rt-n56u.git /opt/rt-n56u
    - name: Build Tool Chain           
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./clean_sources
        sudo ./build_toolchain
        mkdir /opt/images/
    - name: Clear And Build              
      run: |
	      sudo rm -f /opt/rt-n56u/trunk/.config
		    sudo cp /opt/rt-n56u/trunk/configs/templates/ac54u_base.config /opt/rt-n56u/trunk/.config
        mv $GITHUB_WORKSPACE/board.h /opt/rt-n56u/trunk/configs/boards/RT-AC54U/board.h
		    mv $GITHUB_WORKSPACE/kernel-3.4.x.config /opt/rt-n56u/trunk/configs/boards/RT-AC54U/kernel-3.4.x.config
	    	mv $GITHUB_WORKSPACE/board.mk /opt/rt-n56u/trunk/configs/boards/RT-AC54U/board.mk
		    mv $GITHUB_WORKSPACE/defaults.h /opt/rt-n56u/trunk/user/shared/defaults.h
		    mv $GITHUB_WORKSPACE/MT7620_AP_2T2R-4L_external_LNA_external_PA_V15.bin /opt/rt-n56u/trunk/vendors/Ralink/MT7620/MT7620_AP_2T2R-4L_external_LNA_external_PA_V15.bin
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware
        sudo mv -f images/*.trx /opt/images/       
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
